name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test with RTL
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Run Tests
        working-directory: ./frontend
        run: npm run test:ci
        env:
          CI: true

  deployment:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/bankapp"
